package com.helios.testforge.ddl;

import com.helios.testforge.domain.schema.CheckConstraint;
import com.helios.testforge.domain.schema.ColumnMeta;
import com.helios.testforge.domain.schema.ForeignKey;
import com.helios.testforge.domain.schema.SchemaSnapshot;
import com.helios.testforge.domain.schema.TableMeta;
import com.helios.testforge.domain.schema.UniqueConstraint;
import com.helios.testforge.util.Pg;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Re-emits an introspected schema as DDL for the ephemeral database.
 *
 * <p>Statements come out in a deliberate order — enum types, then tables with
 * only their column definitions, then every constraint as a separate ALTER —
 * so table creation never depends on table order. That sidesteps the ordering
 * problem entirely at DDL time; the topological sort is needed for <em>rows</em>,
 * not for structure.
 *
 * <p>Two deliberate divergences from the source schema:
 *
 * <ul>
 *   <li>{@code serial} columns are re-emitted as {@code GENERATED BY DEFAULT AS
 *       IDENTITY}. Reproducing a serial faithfully means creating and owning a
 *       separate sequence object; an identity column is the modern spelling of
 *       the same thing, needs no extra object, and still lets the seeder supply
 *       explicit values so generated keys match the plan.</li>
 *   <li>Foreign keys are created {@code DEFERRABLE INITIALLY IMMEDIATE}. That
 *       changes nothing about normal inserts, but it lets the seeder defer
 *       constraint checking inside a transaction when it fills a cycle-breaking
 *       column, without having to drop and recreate the constraint.</li>
 * </ul>
 */
@Component
public class DdlWriter {

    /**
     * Renders the full DDL script for a snapshot.
     *
     * @param snapshot the schema to reproduce
     * @return statements in application order, without trailing semicolons
     */
    public List<String> write(SchemaSnapshot snapshot) {
        List<String> statements = new ArrayList<>();

        statements.add("CREATE SCHEMA IF NOT EXISTS " + Pg.quoteIdentifier(snapshot.schema()));
        statements.addAll(enumTypes(snapshot));

        for (TableMeta table : snapshot.tables()) {
            statements.add(createTable(table));
        }
        for (TableMeta table : snapshot.tables()) {
            statements.addAll(primaryKey(table));
            statements.addAll(uniqueConstraints(table));
        }
        for (TableMeta table : snapshot.tables()) {
            statements.addAll(foreignKeys(table, snapshot));
            statements.addAll(checkConstraints(table));
        }
        return statements;
    }

    /** The DDL as a single runnable script, for snapshot bundles and the console's preview. */
    public String writeScript(SchemaSnapshot snapshot) {
        StringBuilder script = new StringBuilder();
        script.append("-- Generated by TestForge from ")
                .append(snapshot.database()).append('.').append(snapshot.schema())
                .append(" (fingerprint ").append(snapshot.fingerprint()).append(")\n")
                .append("-- ").append(snapshot.tableCount()).append(" tables, ")
                .append(snapshot.columnCount()).append(" columns, ")
                .append(snapshot.foreignKeyCount()).append(" foreign keys\n\n");
        for (String statement : write(snapshot)) {
            script.append(statement).append(";\n\n");
        }
        return script.toString();
    }

    // ------------------------------------------------------------- sections

    /**
     * One CREATE TYPE per distinct enum used by any column. Labels keep their
     * catalog sort order, because an enum's order is part of its semantics —
     * comparisons and ORDER BY depend on it.
     */
    private List<String> enumTypes(SchemaSnapshot snapshot) {
        Map<String, List<String>> enums = new LinkedHashMap<>();
        for (TableMeta table : snapshot.tables()) {
            for (ColumnMeta column : table.columns()) {
                if (column.isEnum()) {
                    enums.putIfAbsent(column.udtName(), column.enumLabels());
                }
            }
        }
        List<String> statements = new ArrayList<>(enums.size());
        enums.forEach((typeName, labels) -> {
            String values = labels.stream().map(Pg::quoteLiteral).reduce((a, b) -> a + ", " + b).orElse("");
            statements.add("CREATE TYPE " + Pg.quoteIdentifier(snapshot.schema()) + "."
                    + Pg.quoteIdentifier(typeName) + " AS ENUM (" + values + ")");
        });
        return statements;
    }

    private String createTable(TableMeta table) {
        StringBuilder sql = new StringBuilder("CREATE TABLE ").append(table.ref().quoted()).append(" (\n");
        List<String> definitions = new ArrayList<>(table.columns().size());
        for (ColumnMeta column : table.columns()) {
            definitions.add("    " + columnDefinition(column));
        }
        sql.append(String.join(",\n", definitions)).append("\n)");
        return sql.toString();
    }

    String columnDefinition(ColumnMeta column) {
        StringBuilder definition = new StringBuilder(Pg.quoteIdentifier(column.name()))
                .append(' ').append(column.formattedType());

        if (column.generated() && column.generationExpression() != null) {
            definition.append(" GENERATED ALWAYS AS (").append(column.generationExpression()).append(") STORED");
        } else if (column.identity()) {
            definition.append(" GENERATED ").append(column.identityGeneration()).append(" AS IDENTITY");
        } else if (column.serial()) {
            // See the class comment: a serial becomes an identity column.
            definition.append(" GENERATED BY DEFAULT AS IDENTITY");
        } else if (column.defaultExpression() != null) {
            definition.append(" DEFAULT ").append(column.defaultExpression());
        }

        if (!column.nullable()) {
            definition.append(" NOT NULL");
        }
        return definition.toString();
    }

    private List<String> primaryKey(TableMeta table) {
        return table.primaryKeyOpt()
                .map(pk -> List.of("ALTER TABLE " + table.ref().quoted()
                        + " ADD CONSTRAINT " + Pg.quoteIdentifier(pk.name())
                        + " PRIMARY KEY (" + quotedColumns(pk.columns()) + ")"))
                .orElseGet(List::of);
    }

    /**
     * UNIQUE constraints are re-emitted as constraints; unique <em>indexes</em>
     * are re-emitted as indexes. Collapsing the two would change the schema the
     * requester is testing against — an index can be dropped concurrently, a
     * constraint cannot.
     */
    private List<String> uniqueConstraints(TableMeta table) {
        List<String> statements = new ArrayList<>(table.uniques().size());
        for (UniqueConstraint unique : table.uniques()) {
            if (unique.fromIndex()) {
                statements.add("CREATE UNIQUE INDEX " + Pg.quoteIdentifier(unique.name())
                        + " ON " + table.ref().quoted() + " (" + quotedColumns(unique.columns()) + ")");
            } else {
                statements.add("ALTER TABLE " + table.ref().quoted()
                        + " ADD CONSTRAINT " + Pg.quoteIdentifier(unique.name())
                        + " UNIQUE (" + quotedColumns(unique.columns()) + ")");
            }
        }
        return statements;
    }

    /** Foreign keys whose parent is outside the snapshot are skipped: the table does not exist to point at. */
    private List<String> foreignKeys(TableMeta table, SchemaSnapshot snapshot) {
        List<String> statements = new ArrayList<>();
        for (ForeignKey fk : table.foreignKeys()) {
            if (snapshot.table(fk.parent()).isEmpty()) {
                continue;
            }
            statements.add("ALTER TABLE " + table.ref().quoted()
                    + " ADD CONSTRAINT " + Pg.quoteIdentifier(fk.name())
                    + " FOREIGN KEY (" + quotedColumns(fk.childColumns()) + ")"
                    + " REFERENCES " + fk.parent().quoted() + " (" + quotedColumns(fk.parentColumns()) + ")"
                    + " ON DELETE " + fk.onDelete()
                    + " ON UPDATE " + fk.onUpdate()
                    + " DEFERRABLE INITIALLY IMMEDIATE");
        }
        return statements;
    }

    /**
     * Check constraints are re-emitted verbatim from {@code pg_get_constraintdef},
     * which already renders them as {@code CHECK (...)}.
     */
    private List<String> checkConstraints(TableMeta table) {
        List<String> statements = new ArrayList<>(table.checks().size());
        for (CheckConstraint check : table.checks()) {
            statements.add("ALTER TABLE " + table.ref().quoted()
                    + " ADD CONSTRAINT " + Pg.quoteIdentifier(check.name())
                    + " " + check.expression());
        }
        return statements;
    }

    private static String quotedColumns(List<String> columns) {
        return columns.stream().map(Pg::quoteIdentifier).reduce((a, b) -> a + ", " + b).orElse("");
    }
}
