package com.helios.testforge.ddl;

import com.helios.testforge.domain.schema.SchemaSnapshot;
import com.helios.testforge.support.SchemaFixtures;
import org.junit.jupiter.api.Test;

import java.util.List;

import static com.helios.testforge.support.SchemaFixtures.table;
import static org.assertj.core.api.Assertions.assertThat;

class DdlWriterTest {

    private final DdlWriter writer = new DdlWriter();

    @Test
    void createsEveryTableBeforeAnyForeignKey() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(
                table("customer"),
                table("order_header").references("customer_id", "customer", false));

        List<String> statements = writer.write(snapshot);

        int lastCreate = lastIndexMatching(statements, "CREATE TABLE");
        int firstForeignKey = firstIndexMatching(statements, "FOREIGN KEY");
        assertThat(firstForeignKey)
                .as("foreign keys must come after every CREATE TABLE, so table order cannot matter")
                .isGreaterThan(lastCreate);
    }

    @Test
    void rewritesSerialColumnsAsIdentityColumns() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(table("widget"));

        String createTable = writer.write(snapshot).stream()
                .filter(s -> s.startsWith("CREATE TABLE"))
                .findFirst()
                .orElseThrow();

        assertThat(createTable).contains("GENERATED BY DEFAULT AS IDENTITY");
        assertThat(createTable).doesNotContain("nextval");
    }

    @Test
    void emitsEnumTypesBeforeTheTablesUsingThem() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(
                table("shipment").enumColumn("status", false, "PENDING", "SHIPPED", "DELIVERED"));

        List<String> statements = writer.write(snapshot);

        int createType = firstIndexMatching(statements, "CREATE TYPE");
        int createTable = firstIndexMatching(statements, "CREATE TABLE");
        assertThat(createType).isGreaterThanOrEqualTo(0).isLessThan(createTable);
        assertThat(statements.get(createType))
                .contains("'PENDING'", "'SHIPPED'", "'DELIVERED'")
                .contains("AS ENUM");
    }

    @Test
    void makesForeignKeysDeferrableSoCycleFixupsCanRunInOneTransaction() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(
                table("a"),
                table("b").references("a_id", "a", false));

        assertThat(writer.write(snapshot))
                .filteredOn(s -> s.contains("FOREIGN KEY"))
                .allMatch(s -> s.contains("DEFERRABLE INITIALLY IMMEDIATE"));
    }

    @Test
    void skipsForeignKeysWhoseParentIsNotInTheSnapshot() {
        SchemaSnapshot full = SchemaFixtures.snapshot(
                table("region"),
                table("store").references("region_id", "region", true));
        SchemaSnapshot subset = full.restrictedTo(List.of(SchemaFixtures.ref("store")));

        assertThat(writer.write(subset))
                .as("the parent table does not exist in the ephemeral database, so the constraint cannot be created")
                .noneMatch(s -> s.contains("FOREIGN KEY"));
    }

    @Test
    void quotesEveryIdentifier() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(table("order"));

        assertThat(writer.write(snapshot))
                .filteredOn(s -> s.startsWith("CREATE TABLE"))
                .allMatch(s -> s.contains("\"public\".\"order\""));
    }

    @Test
    void emitsUniqueConstraintsAndIndexesDistinctly() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(
                table("account").column("email", "varchar", false).unique("email"));

        assertThat(writer.write(snapshot))
                .anyMatch(s -> s.contains("ADD CONSTRAINT") && s.contains("UNIQUE"));
    }

    @Test
    void writesARunnableScriptWithAProvenanceHeader() {
        SchemaSnapshot snapshot = SchemaFixtures.snapshot(table("thing"));

        String script = writer.writeScript(snapshot);

        assertThat(script).startsWith("-- Generated by TestForge from testdb.public");
        assertThat(script).contains("fingerprint fixture");
        assertThat(script.lines().filter(l -> l.endsWith(";")).count()).isGreaterThan(0);
    }

    private static int firstIndexMatching(List<String> statements, String needle) {
        for (int i = 0; i < statements.size(); i++) {
            if (statements.get(i).contains(needle)) {
                return i;
            }
        }
        return -1;
    }

    private static int lastIndexMatching(List<String> statements, String needle) {
        int found = -1;
        for (int i = 0; i < statements.size(); i++) {
            if (statements.get(i).contains(needle)) {
                found = i;
            }
        }
        return found;
    }
}
